FROM --platform=$BUILDPLATFORM golang:1.24-alpine AS builder
WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -buildvcs=false -o /donetick .

FROM donetick/donetick:v0.1.79
COPY --from=builder /donetick /donetick
